import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDownLeft, ArrowUpRight, ArrowRight, CarFront, LayoutDashboard, History, ParkingSquare, Search, Plus, X, Download, RefreshCw, CircleHelp, LogOut, Check, LoaderCircle } from 'lucide-react';
import './style.css';

const money = cents => (cents / 100).toLocaleString('pt-BR', {style:'currency', currency:'BRL'});
const duration = seconds => { const m = Math.floor(seconds/60); return m < 60 ? `${m} min` : `${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}min`; };
const hour = ts => new Date(ts*1000).toLocaleTimeString('pt-BR', {hour:'2-digit',minute:'2-digit'});
const date = ts => new Date(ts*1000).toLocaleString('pt-BR', {dateStyle:'short',timeStyle:'short'});

function App() {
  const [token, setToken] = useState(sessionStorage.getItem('parking-token') || '');
  const [loginToken,setLoginToken] = useState('');
  const [demo,setDemo] = useState(false);
  const [view,setView] = useState('overview');
  const [data,setData] = useState(null);
  const [history,setHistory] = useState({items:[],total:0});
  const [page,setPage] = useState(1);
  const [search,setSearch] = useState('');
  const [modal,setModal] = useState(null);
  const [quote,setQuote] = useState(null);
  const [entry,setEntry] = useState({plate:'',vehicle:'',spot_id:''});
  const [payment,setPayment] = useState('pix');
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState('');
  const [notice,setNotice] = useState('');

  async function api(path, options={}) {
    const r = await fetch('/api'+path, {...options,headers:{'Authorization':`Bearer ${token}`,'Content-Type':'application/json',...options.headers}});
    if(!r.ok) {
      const body = await r.json().catch(()=>({detail:'Não foi possível completar a solicitação.'}));
      if(r.status===401) {sessionStorage.removeItem('parking-token');setToken('');setData(null);}
      throw new Error(Array.isArray(body.detail) ? body.detail.map(e=>e.msg.replace('Value error, ', '')).join(' ') : body.detail);
    }
    return r;
  }
  async function load() {
    const result=await (await api('/overview')).json();setData(result);setDemo(result.demo);
  }
  useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(d=>setDemo(d.demo)).catch(()=>setError('API indisponível. Confira se o servidor está em execução.'));},[]);
  useEffect(()=>{
    if(!token)return;
    load().catch(e=>setError(e.message));
    const timer=setInterval(()=>load().catch(e=>setError(e.message)),30000);
    return ()=>clearInterval(timer);
  },[token]);
  useEffect(()=>{
    if(!token||view!=='history')return;
    let current=true;
    api(`/history?page=${page}&search=${encodeURIComponent(search)}`)
      .then(r=>r.json()).then(result=>{if(current)setHistory(result);})
      .catch(e=>{if(current)setError(e.message);});
    return()=>{current=false;};
  },[view,page,search,token]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t);},[notice]);
  useEffect(()=>{
    if(!modal)return;
    const previous=document.activeElement;
    const dialog=document.querySelector('[role="dialog"]');
    const focusables=()=>[...dialog.querySelectorAll('button:not([disabled]), input, select')];
    focusables()[0]?.focus();
    function key(e){if(e.key==='Escape'&&!busy){setModal(null);setError('');} if(e.key==='Tab'){const f=focusables(),first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
    document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};
  },[modal,busy]);
  function login(value){setError('');sessionStorage.setItem('parking-token',value);setToken(value);}
  function openEntry(spot=''){setEntry({plate:'',vehicle:'',spot_id:spot});setError('');setModal('entry');}
  async function action(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function checkoutPreview(stay){await action(async()=>{setQuote(await (await api(`/stays/${stay.id}/quote`)).json());setPayment('pix');setModal('exit');});}
  async function register(e){e.preventDefault();await action(async()=>{await api('/stays',{method:'POST',body:JSON.stringify({...entry,spot_id:entry.spot_id?Number(entry.spot_id):null})});await load();setModal(null);setNotice('Entrada registrada. A vaga já está reservada.');});}
  async function finish(){await action(async()=>{const receipt=await (await api(`/stays/${quote.id}/checkout`,{method:'POST',body:JSON.stringify({expected_cents:quote.amount_cents,payment_method:payment})})).json();setQuote(receipt);await load();setModal('receipt');});}
  async function download(){await action(async()=>{const blob=await (await api('/history.csv')).blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='movimentacoes.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
  const filtered=data?.active.filter(s=>`${s.plate} ${s.vehicle}`.toUpperCase().includes(search.toUpperCase())) || [];
  const titles={overview:'Visão geral',history:'Movimentações',rates:'Tarifas e regras'};

  if(!token)return <div className="login"><div className="login-brand"><ParkingSquare size={40}/><h1>Vaga Certa<span>Menos filas. Mais controle.</span></h1></div><div className="login-card"><p className="eyebrow">BEM-VINDO À OPERAÇÃO</p><h2>Seu estacionamento,<br/>em um só lugar.</h2><p>Entradas, vagas e recebimentos sem perder o ritmo.</p><form onSubmit={e=>{e.preventDefault();login(loginToken);}}><label>Token do operador<input type="password" required value={loginToken} onChange={e=>setLoginToken(e.target.value)} placeholder="Informe seu acesso"/></label><button className="primary full">Acessar painel <ArrowRight size={17}/></button></form>{demo&&<button className="secondary full" onClick={()=>login('demo-local')}>Explorar demonstração</button>}{error&&<p role="alert" className="error">{error}</p>}<small>Projeto de portfólio · Demonstração com dados fictícios</small></div></div>;

  return <div className="shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>e.preventDefault()}><span className="brand-mark">P<span>•</span></span><span>vaga certa<small>GESTÃO DE ESTACIONAMENTO</small></span></a><div className="unit"><span className="unit-icon"><CarFront size={19}/></span><div>Unidade Centro<small>Operação local</small></div><span className="live-dot"/></div><p className="nav-label">ESPAÇO DE TRABALHO</p><nav>{[['overview',LayoutDashboard,'Visão geral'],['history',History,'Movimentações'],['rates',CircleHelp,'Tarifas e regras']].map(([id,Icon,label])=><button key={id} className={view===id?'selected':''} onClick={()=>{setView(id);setSearch('');setPage(1);setError('');}}><Icon size={18}/>{label}{view===id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-note"><div className="mini-grid">▦</div><strong>Espaço para o que importa.</strong><p>Acompanhe cada vaga, da chegada à saída.</p></div><div className="operator"><span className="avatar">OP</span><div>Operador<small>{demo?'Modo demonstração':'Acesso autorizado'}</small></div><button aria-label="Sair da conta" onClick={()=>{sessionStorage.removeItem('parking-token');setToken('');setData(null);}}><LogOut size={17}/></button></div></aside>
  <div className="workspace"><header className="topbar"><span>Operação <span className="slash">/</span> <strong>{titles[view]}</strong></span><div><span className="status-pill"><i/> {demo?'Demonstração':'Operador conectado'}</span><span className="top-date">{new Date().toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'})}</span></div></header><main><section className="page-heading"><div><p className="eyebrow">CONTROLE DO DIA A DIA</p><h1>{titles[view]}</h1><p>{view==='overview'?'Uma visão clara do movimento, em tempo real.':view==='history'?'Cada saída registrada. Tudo pronto para conferir.':'Regras simples, cobranças previsíveis.'}</p></div>{view==='overview'?<button className="primary" disabled={!data||busy||data.occupied>=data.capacity} onClick={()=>openEntry()}><Plus size={18}/> Registrar entrada</button>:view==='history'?<button className="secondary" disabled={busy} onClick={download}><Download size={17}/> Exportar CSV</button>:null}</section>
  {error&&!modal&&<div className="error" role="alert">{error}<button onClick={()=>action(load)}>Tentar novamente</button></div>}{notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}
  {!data?<div className="loading"><LoaderCircle className="spin"/> Carregando operação…</div>:<>
  {view==='overview'&&<><section className="metrics"><Metric icon={CarFront} title="Veículos no pátio" value={String(data.occupied).padStart(2,'0')} note={`${Math.round(data.occupied/data.capacity*100)}% da capacidade ocupada`} color="green"/><Metric icon={ParkingSquare} title="Vagas disponíveis" value={String(data.capacity-data.occupied).padStart(2,'0')} note={`De ${data.capacity} vagas no total`} color="sage"/><Metric icon={ArrowDownLeft} title="Recebimentos de hoje" value={money(data.today_cents)} note="Saídas confirmadas · horário de São Paulo" color="orange"/></section>
  <section className="middle"><article className="card parking"><div className="card-heading"><div><h2>Mapa de vagas</h2><p>Selecione uma vaga livre para registrar a entrada.</p></div><span className="outline-pill">SETOR A</span></div><div className="legend"><span><i className="free"/>Livre</span><span><i className="taken"/>Ocupada</span></div><div className="spots">{data.spots.map(s=><button key={s.id} className={`spot ${s.plate?'occupied':''}`} title={s.plate?`${s.label} · ${s.plate}`:`Registrar entrada na vaga ${s.label}`} aria-label={s.plate?`Vaga ${s.label}, ocupada por ${s.plate}`:`Vaga ${s.label}, livre`} onClick={()=>s.plate?checkoutPreview(data.active.find(a=>a.spot_id===s.id)):openEntry(s.id)}><CarFront size={23}/><span>{s.label}</span></button>)}</div><div className="driveway"><span>ENTRADA</span><span className="road-line"/><ArrowRight size={16}/><span className="road-line"/><span>SAÍDA</span></div></article><article className="card revenue"><div className="card-heading"><div><h2>Recebimentos</h2><p>Últimos 7 dias</p></div><span className="small-icon"><ArrowUpRight size={19}/></span></div><strong className="revenue-total">{money(data.revenue.reduce((n,d)=>n+d.amount_cents,0))}</strong><span className="muted small">Total registrado no período</span><div className="chart" role="img" aria-label="Recebimentos dos últimos sete dias">{data.revenue.map((day,i)=><div key={day.date} className="chart-column"><div className={`bar ${i===6?'today':''}`} style={{height:`${Math.max(3,day.amount_cents/Math.max(1,...data.revenue.map(d=>d.amount_cents))*112)}px`}} title={`${day.date}: ${money(day.amount_cents)}`}><span>{money(day.amount_cents)}</span></div><small>{day.date}</small></div>)}</div><div className="chart-foot"><span className="live-dot"/> Hoje: {money(data.today_cents)}</div></article></section>
  <article className="card vehicles"><div className="card-heading"><div className="inline"><h2>No estacionamento</h2><span className="count">{data.occupied}</span></div><label className="search"><Search size={16}/><input aria-label="Buscar placa ou veículo" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar placa ou veículo"/></label></div><div className="table-scroll"><table><thead><tr><th>VEÍCULO</th><th>VAGA</th><th>ENTRADA</th><th>PERMANÊNCIA</th><th>PRÉVIA</th><th/></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><div className="vehicle-cell"><span className="car-tile"><CarFront size={20}/></span><div><strong className="plate">{s.plate}</strong><small>{s.vehicle||'Veículo não informado'}</small></div></div></td><td><span className="spot-tag">{s.spot}</span></td><td>{hour(s.entered_at)}</td><td>{duration(s.duration_seconds)}</td><td className="amount">{money(s.amount_cents)}</td><td><button className="text-button" disabled={busy} onClick={()=>checkoutPreview(s)}>Registrar saída <ArrowUpRight size={15}/></button></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="empty"><CarFront size={27}/><strong>{search?'Nenhum veículo encontrado':'Seu pátio está livre'}</strong><p>{search?'Tente buscar por outra placa.':'Registre uma entrada para começar a operação.'}</p>{demo&&!search&&<button className="secondary" disabled={busy} onClick={()=>action(async()=>{await api('/demo',{method:'POST'});await load();setNotice('Demonstração carregada com dados fictícios.');})}>Carregar dados de exemplo</button>}</div>}<div className="table-foot"><span>Atualização automática a cada 30 segundos</span><button onClick={()=>action(load)} disabled={busy}><RefreshCw size={13}/> Atualizar</button></div></article></>}
  {view==='history'&&<article className="card vehicles"><div className="card-heading"><h2>Saídas concluídas <span className="count">{history.total}</span></h2><label className="search"><Search size={16}/><input aria-label="Buscar no histórico" placeholder="Buscar placa" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label></div><div className="table-scroll"><table><thead><tr><th>PLACA</th><th>VAGA</th><th>ENTRADA</th><th>SAÍDA</th><th>FORMA</th><th>VALOR</th></tr></thead><tbody>{history.items.map(s=><tr key={s.id}><td className="plate">{s.plate}</td><td>{s.spot}</td><td>{date(s.entered_at)}</td><td>{date(s.exited_at)}</td><td>{{pix:'Pix',card:'Cartão',cash:'Dinheiro'}[s.payment_method]}</td><td className="amount">{money(s.amount_cents)}</td></tr>)}</tbody></table></div>{!history.items.length&&<div className="empty"><History/><strong>Nenhuma saída encontrada</strong><p>As saídas confirmadas aparecem aqui.</p></div>}<div className="table-foot"><button disabled={page===1} onClick={()=>setPage(page-1)}>← Anterior</button><span>Página {page}</span><button disabled={page*20>=history.total} onClick={()=>setPage(page+1)}>Próxima →</button></div></article>}
  {view==='rates'&&<section className="rules"><article className="card"><p className="eyebrow">TABELA ATUAL</p><h2>Cobrança por permanência</h2><div className="rule-row"><span>Primeira hora</span><strong>{money(data.tariff.first_hour)}</strong></div><div className="rule-row"><span>Cada hora adicional iniciada</span><strong>{money(data.tariff.extra_hour)}</strong></div><div className="rule-row"><span>Tolerância de saída gratuita</span><strong>{data.tariff.grace_minutes} minutos</strong></div><p>Após a tolerância, a cobrança considera todo o tempo desde a entrada. Exemplo: 10 minutos = R$ 0; 11 minutos = R$ 12; 61 minutos = R$ 18.</p></article><article className="card"><p className="eyebrow">COMO FUNCIONA</p><h2>Da entrada à conferência</h2><ol><li>Registre a placa e escolha uma vaga livre.</li><li>Confira a prévia de cobrança ao registrar a saída.</li><li>Informe como o valor foi recebido e confirme.</li><li>Consulte o histórico ou exporte para CSV.</li></ol><p>O sistema registra recebimentos informados pelo operador. Não processa pagamentos, não emite nota fiscal e não consulta dados da placa.</p></article></section>}
  </>}<footer>Vaga Certa <span>•</span> Gestão simples, do primeiro ao último veículo.<span className="footer-right">{demo?'DADOS DE DEMONSTRAÇÃO':'OPERAÇÃO'}</span></footer></main></div>
  {modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy){setModal(null);setError('');}}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="close" aria-label="Fechar" disabled={busy} onClick={()=>{setModal(null);setError('');}}><X size={21}/></button><p className="eyebrow">{modal==='entry'?'NOVA CHEGADA':modal==='receipt'?'TUDO CERTO':'FINALIZAR ESTADIA'}</p><h2 id="modal-title">{modal==='entry'?'Registrar entrada':modal==='receipt'?'Saída registrada':'Conferir saída'}</h2>{modal==='entry'?<form onSubmit={register}><label>Placa<input autoComplete="off" required maxLength={10} value={entry.plate} onChange={e=>setEntry({...entry,plate:e.target.value.toUpperCase()})} placeholder="ABC1D23"/></label><label>Modelo e cor <span className="muted">(opcional)</span><input maxLength={60} value={entry.vehicle} onChange={e=>setEntry({...entry,vehicle:e.target.value})} placeholder="Ex.: Honda Civic · prata"/></label><label>Vaga<select value={entry.spot_id} onChange={e=>setEntry({...entry,spot_id:e.target.value})}><option value="">Selecionar automaticamente</option>{data.spots.filter(s=>!s.plate).map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><p className="form-note">10 minutos de tolerância · Primeira hora R$ 12,00</p><button className="primary full" disabled={busy}>{busy?'Registrando…':'Confirmar entrada'}<ArrowRight size={17}/></button></form>:<><div className="quote-vehicle"><CarFront/><div><strong className="plate">{quote.plate}</strong><small>{quote.vehicle||'Veículo'} · Vaga {quote.spot}</small></div></div><div className="rule-row"><span>Permanência</span><strong>{duration(quote.duration_seconds)}</strong></div><div className="quote-total"><span>{modal==='receipt'?'Valor registrado':'Total previsto'}</span><strong>{money(quote.amount_cents)}</strong></div>{modal==='exit'?<><label>Forma de recebimento<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="pix">Pix</option><option value="card">Cartão</option><option value="cash">Dinheiro</option></select></label><p className="form-note">Confirme após conferir o recebimento. A vaga será liberada.</p><button className="primary full" disabled={busy} onClick={finish}>{busy?'Confirmando…':'Confirmar saída'}<Check size={17}/></button><button className="text-button full" disabled={busy} onClick={()=>checkoutPreview(quote)}><RefreshCw size={14}/> Atualizar prévia</button></>:<><p className="form-note">Registro #{quote.id} · {date(quote.exited_at)}<br/>A vaga {quote.spot} está disponível novamente.</p><button className="primary full" onClick={()=>setModal(null)}>Voltar à operação</button></>}</>}{error&&<p className="error" role="alert">{error}</p>}</section></div>}
  </div>;
}
function Metric({icon:Icon,title,value,note,color}){return <article className={`metric ${color}`}><div className="metric-top"><span>{title}</span><Icon size={20}/></div><strong>{value}</strong><small>{note}</small></article>;}

createRoot(document.getElementById('root')).render(<App/>);
